import type { Metadata } from "next";
import "./globals.css";
import AuthSession from "@/providers/sessionProvider";
import Script from "next/script";
import React from "react";
import NavBar from "../components/Layout/NavBar";

const KAKAO_SDK_URL = "https://developers.kakao.com/sdk/js/kakao.js";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  // eslint-disable-next-line no-unused-vars
  interface Window {
    Kakao: any;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-center">
          <div className="w-full max-w-screen-md pt-10 bg-beige-100">
            <AuthSession>
              <div className="px-4">{children}</div>
              <NavBar />
            </AuthSession>
            <Script src={KAKAO_SDK_URL} />
          </div>
        </div>
      </body>
    </html>
  );
}
