import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthSession from "@/providers/sessionProvider";
import Script from "next/script";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

const KAKAO_SDK_URL = "https://developers.kakao.com/sdk/js/kakao.js";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  // eslint-disable-next-line no-unused-vars
  interface Window {
    Kakao: any;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSession>{children}</AuthSession>
        <Script src={KAKAO_SDK_URL} />
      </body>
    </html>
  );
}
